Pin @types/node to 6.0.42 for yelb-ui
Latest versions of Node.js lead to the following exception when building yelb-ui Docker image:
node_modules/@types/node/index.d.ts(20,1): error TS1084: Invalid 'reference' directive syntax.

Pinning to 6.0.42 version (instead of ^) solves the issue.